FROM debian:jessie
RUN apt-get update && apt-get install -y unzip wget tar build-essential zip git

RUN mkdir -p /opt
WORKDIR /opt

RUN wget --quiet https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz  
RUN tar -C /usr/local -xzf go1.8.1.linux-amd64.tar.gz  

RUN mkdir -p /code/go/src/distcron
ENV GOPATH "/code/go"
ENV PATH "/usr/local/go/bin:$PATH:$GOPATH/bin"

RUN mkdir -p /opt/protoc
WORKDIR /opt/protoc
RUN wget --quiet https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
RUN unzip protoc-3.2.0-linux-x86_64.zip
ENV PATH "$PATH:/opt/protoc/bin"

RUN go get google.golang.org/grpc
RUN go get -u github.com/golang/protobuf/proto github.com/golang/protobuf/protoc-gen-go

RUN go get -u github.com/kardianos/govendor

WORKDIR /code/go/src/distcron