FROM debian:jessie
RUN apt-get update && apt-get install -y unzip wget

RUN wget --quiet https://releases.hashicorp.com/consul/0.8.1/consul_0.8.1_linux_amd64.zip
RUN unzip consul_0.8.1_linux_amd64.zip
EXPOSE 8500 